apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: {{ include "wordpress-site.fullname" . }}
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    helm.sh/chart: {{ include "wordpress-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.image }}
  image: {{ .Values.image.repository }}
  tag: {{ .Values.image.tag }}
  imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
  {{- if .Values.image.imagePullSecrets }}
  imagePullSecrets: {{ .Values.image.imagePullSecrets }}
  {{- end }}
  {{- end }}
  domains:
    {{- toYaml .Values.site.domains | nindent 4 }}
  tlsSecretRef: {{ include "wordpress-site.fullname" . }}-tls
  {{- if .Values.code }}
  code:
    readOnly: {{ .Values.code.readOnly }}
    contentSubPath: {{ .Values.code.contentSubPath }}
    {{- if .Values.code.git }}
    git:
      repository: {{ required "A valid code.git.repository is required!" .Values.code.git.repository | quote }}
      reference: {{ default "master" .Values.code.git.reference }}
      env:
        - name: SSH_RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}
              key: id_rsa
    {{- end }}
  {{- end }}
  {{- if and .Values.media .Values.media.gcs }}
  media:
    gcs:
      bucket: {{ required "A valid media.gcs.bucket is required!" .Values.media.gcs.bucket | quote }}
      prefix: {{ default "" .Values.media.gcs.prefix | quote }}
      env:
        - name: GOOGLE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-site.fullname" . }}
              key: google_application_credentials.json
        - name: GOOGLE_PROJECT_ID
          value: {{ required "A valid media.gcs.project is required!" .Values.media.gcs.project | quote }}
  {{- end }}
  env:
    - name: MEMCACHED_DISCOVERY_HOST
      value: {{ include "wordpress-site.fullname" . }}-memcached
    - name: DB_HOST
      value: {{ include "wordpress-site.fullname" . }}-mysql-master
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: {{ include "wordpress-site.fullname" . }}-db
          key: DATABASE
  {{- if .Values.site.env }}
    {{- toYaml .Values.site.env | nindent 4 }}
  {{- end }}
  {{- if .Values.site.envFrom }}
  envFrom:
    {{- toYaml .Values.site.envFrom | nindent 4 }}
  {{- end }}
  {{- if .Values.site.resources }}
  resources:
    {{- toYaml .Values.site.resources | nindent 4 }}
  {{- end }}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/wordpress
            operator: Exists
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: wordpress
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/part-of: wordpress
  tolerations:
    - key: "cloud.google.com/gke-preemptible"
      operator: "Exists"
  ingressAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    {{- if eq "ClusterIssuer" (default "ClusterIssuer" .Values.tls.issuerKind) }}
    certmanager.k8s.io/cluster-issuer: {{ default "stack-default" .Values.tls.issuerName }}
    {{- else if eq "Issuer" (default "ClusterIssuer" .Values.tls.issuerKind) }}
    certmanager.k8s.io/issuer: {{ default "stack-default" .Values.tls.issuerName }}
    {{- end }}
    certmanager.k8s.io/acme-challenge-type: {{ default "http01" .Values.tls.acmeChallengeType }}
