wordpress-operator:
  enabled: true

mysql-operator:
  enabled: true
  orchestrator:
    replicas: 1

nginx-ingress:
  enabled: true
  controller:
    config:
      custom-http-errors: 400,401,403,404,415,500,502,503,504
  defaultBackend:
    image:
      repository: quay.io/presslabs/default-backend
      tag: latest

cert-manager:
  enabled: true

prometheus-operator:
  enabled: true
